name: PMD Code Analysis

on:
  push:
    branches:
      - '**'

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Run PMD analysis
      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0-rc4'  # Wajib pake 7.0.0-rc4 krn Java 21
          sourcePath: 'src'
          analyzeModifiedFilesOnly: false
          rulesets: >
            category/java/errorprone.xml,
            category/java/bestpractices.xml,
            category/java/design.xml